### PR TITLE
fix: lazy-load dap when patching

### LINKED ISSUE #212: bug: Setting `dap = false` still loads `nvim-dap` during setup
### Neovim version (nvim -v)

v0.10.0-dev-1260+g9ce162383

### Operating system/version

macOS Sonoma 14.0

### Describe the bug

[The docs describing the DAP integration](https://github.com/stevearc/overseer.nvim/blob/dbc7bcf8c064ec892d99af6ac462fcaeda59da4a/doc/third_party.md?plain=1#L181-L194) say that one can disable the automatic integration when setting up this plugin and setting it up manually later. However, this plugin is [still loading `dap`](https://github.com/stevearc/overseer.nvim/blob/dbc7bcf8c064ec892d99af6ac462fcaeda59da4a/lua/overseer/init.lua#L259) during initialization, disabling lazy-loading.

### Steps To Reproduce

1. Install both `overseer` and `nvim-dap` using their default configurations.
2. Use the configuration provided below.
3. Run `OverseerRun` and notice how `nvim-dap` is also loaded.

### Expected Behavior

For `nvim-dap` to not be loaded when setting up `overseer` if `dap = false`, but instead wait until `patch_dap` is invoked.

### Minimal example file

_No response_

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/dressing.nvim", config = true },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup({
        -- add your overseer config here
        dap = false
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #212 

I removed the `enabled` parameter since this solution assumes that `enabled` is always true when invoking the function.

### CODE REVIEW

File: lua/overseer/init.lua [hunk 1]
```diff
@@ -254,18 +254,13 @@ end
 
 ---Add support for preLaunchTask/postDebugTask to nvim-dap
 ---@private
----@param enabled boolean
-M.patch_dap = function(enabled)
+M.patch_dap = function()
```
Comment (stevearc) [inline lua/overseer/init.lua:257]: I'd prefer if we keep the ability to enable/disable it with a boolean instead of toggling every time it's called. I think we can get the behavior you want by adding a test and an early return here

```lua
if not enabled and not package.loaded.dap then
  return
end
```

**Review by stevearc — CHANGES_REQUESTED** [review]
Thanks for the PR! One request to change the mechanism of the fix

**Comment by stevearc** [comment]
Thanks!

**Comment by MariaSolOs** [comment]
@stevearc thanks to you! So happy to have discovered yet another one of your amazing plugins :)
